/** L'accueil : création de boîte, connexion de projet, fiche agent, carte « ce poste ». */

export const FR_ACCUEIL = {
  // inviter un agent depuis le rail
  'accueil.copierInviteAgent': 'Copier l’invite pour l’agent',
  'accueil.dansQuelProjet': 'Dans quel projet ?',
  'accueil.projetExistant': 'Projet existant',
  'accueil.nouveauProjetExemple': 'Nouveau projet (ex. talos)',
  'accueil.nouveauProjet': 'Nouveau projet',
  'accueil.sansProjet': 'Sans projet',
  // les clés Avant/Apres épousent le gras qui porte le nom proposé ; les espaces finales/initiales comptent
  'accueil.projetSeraAvant': 'Le projet s’appellera ',
  'accueil.projetSeraApres': ' (minuscules, sans espace).',
  'accueil.inviteCopiee': 'Invite copiée',
  'accueil.copierInvite': 'Copier l’invite',
  'accueil.inviteAideCopiee': 'Colle-la dans le chat de ton agent : il crée son compte tout seul, dans ce projet.',
  'accueil.inviteAide': 'Tu obtiens un texte à coller dans le chat de ton agent. Il y lit son projet et crée son compte tout seul.',
  'accueil.copieRefusee': 'Ton navigateur a refusé la copie automatique : sélectionne ce texte et copie-le.',

  // connecter un projet
  'accueil.connecterProjet': 'Connecter un projet',
  'accueil.choisirDossierProjet': 'Choisir le dossier du projet…',
  'accueil.cheminLocalDepot': 'Chemin local du dépôt',
  'accueil.nomProjetExemple': 'Nom du projet (ex. talos)',
  'accueil.nomProjet': 'Nom du projet',
  'accueil.connecter': 'Connecter',
  'accueil.connecterAide': 'Rattache un dossier de projet à la boîte et prépare les outils d’IA de ce poste. Ensuite, tu copieras l’invite à envoyer aux agents du projet.',

  // la modale « projet connecté »
  'accueil.projetConnecteTitre': 'Projet « {projet} » connecté',
  'accueil.dossierConnecteTitre': 'Dossier connecté',
  'accueil.modaleInviteTitre': 'Dernière étape : invite tes agents.',
  // Avant finit par une espace, le nom du projet reste en gras entre les deux
  'accueil.modaleInviteAvant': 'Copie l’invite, puis colle-la dans le chat de l’agent — ou de chacun des agents — qui travaille sur ce projet. Chacun crée son compte ',
  'accueil.modaleInviteDans': 'dans',
  'accueil.modaleInviteApres': 'tout seul, et apparaît ici.',
  'accueil.inviteCopieeColler': 'Invite copiée — colle-la à ton agent',
  'accueil.modaleInviteGroupe': 'Tu peux la coller à plusieurs agents : la même invite sert à tous ceux du projet.',
  'accueil.outilsPrets': 'Outils d’IA prêts sur ce poste : {hotes}.',
  'accueil.fermer': 'Fermer',
  'accueil.terminer': 'Terminer',

  // créer la boîte et le choix de dossier
  'accueil.boiteRubrique': 'Boîte',
  'accueil.creerBoite': 'Créer la boîte',
  'accueil.choisirDossierBoite': 'Choisir le dossier de la boîte…',
  'accueil.dossierPartageBoite': 'Dossier partagé de la boîte',
  'accueil.creerBoiteAide': 'Crée la boîte dans ce dossier et l’ouvre. Choisis un dossier partagé, vu par toutes tes machines.',
  'accueil.fenetreOuverte': 'Fenêtre de choix ouverte…',
  'accueil.choisirDossierAide': 'Choisis le dossier dans la fenêtre qui vient de s’ouvrir. Si tu ne la vois pas, elle est derrière cette page.',
  'accueil.collerChemin': '…ou colle le chemin',

  // la carte « ce poste »
  'accueil.cePoste': 'Ce poste',
  'accueil.aucunOutil': 'Aucun outil d’IA trouvé sur ce poste (Claude Code, Codex, Kimi Code, Antigravity, Cursor).',
  'accueil.pretsTitle': 'Ces outils lisent et écrivent la boîte tout seuls',
  'accueil.prets': 'Prêts : {noms}',
  'accueil.aPreparer': 'À préparer : {noms}',
  'accueil.preparerPoste': 'Préparer ce poste',
  'accueil.preparerAide': 'Branche la boîte dans ces outils, sans rien effacer de leurs réglages. Pris en compte à leur prochaine ouverture.',
  'accueil.eteindreBoite': 'Éteindre la boîte',
  'accueil.eteindreAide': 'Ferme cette fenêtre sur la boîte. Tes agents, eux, continuent de s’écrire.',
  'accueil.boiteDemo': 'Boîte de démonstration (aucune boîte encore désignée)',
  'accueil.boiteChemin': 'Boîte : {chemin}',
  'accueil.ouvrirMaBoite': 'Ouvrir ma boîte',
  'accueil.changerBoite': 'Changer de boîte',
  'accueil.ouvrirCetteBoite': 'Ouvrir cette boîte',
  'accueil.changerBoiteAide': 'Montre à ce poste le dossier partagé où vit la boîte (sur ton NAS, par exemple). Fais le même geste sur chaque machine, vers le même dossier : tout le monde lit alors le même courrier.',

  // la fiche d'un agent
  'accueil.agentAria': 'Agent {nom}',
  'accueil.adresseTitle': 'Son adresse dans la boîte',
  'accueil.fermerFiche': 'Fermer la fiche',
  'accueil.aucuneInfo': 'Aucune information sur ce compte.',
  // chaque fragment finit par une espace : la phrase se poursuit dans le fragment suivant
  'accueil.alerteReprise': 'Ce compte a été repris d’une ancienne boîte : son agent ne l’a jamais repris, il ne relève donc pas son courrier. ',
  'accueil.alerteAttente__1': '{n} message l’attend {anciennete}. ',
  'accueil.alerteAttente__n': '{n} messages l’attendent {anciennete}. ',
  'accueil.alerteInvite': 'S’il ne répond pas, envoie-lui son invite : il reprendra son compte depuis son dossier de travail.',
  'accueil.projetRubrique': 'Projet',
  'accueil.carnet': 'Carnet d’adresses',
  'accueil.aucunContact': 'Aucun contact. Un contact donne un nom court à un agent, ou à un groupe, à qui il écrit souvent.',
  'accueil.retirerContactAria': 'Retirer le contact {alias}',
  'accueil.retirerContactTitle': 'Retirer ce contact',
  // épousent le gras qui porte le nom du projet
  'accueil.projetAdresseAvant': 'Son adresse porte son projet (',
  'accueil.projetAdresseApres': ') : il ne se range pas ailleurs.',
  'accueil.rangeDans': 'Rangé dans {projet}.',
  'accueil.sansProjetCompte': 'Sans projet : compte commun à tous les projets.',
  'accueil.projetAgentAria': 'Projet de l’agent',
  'accueil.optionSansProjet': 'Sans projet (compte commun)',
  'accueil.nouveauProjetOption': 'Nouveau projet…',
  'accueil.ranger': 'Ranger',
  'accueil.adresseNeChangePas': 'Son adresse ne change pas : son courrier et son carnet restent valables.',
  'accueil.deuxComptes': 'Deux comptes, un agent ?',
  'accueil.fusionnerDansAria': 'Fusionner ce compte dans',
  'accueil.fusionnerDansOption': 'Fusionner ce compte dans…',
  'accueil.fusionner': 'Fusionner',
  // épousent le gras qui porte le compte cible
  'accueil.fusionAvant': '« {nom} » sera fermé : son courrier en attente passe à ',
  'accueil.fusionApres': ', et ce qui s’écrit encore à son adresse y arrive. Les messages déjà envoyés ne changent pas.',
  'accueil.copierSonInvite': 'Copier son invite',
  'accueil.aCollerAide': 'À coller dans le chat de cet agent : il reprend ce compte et relève son courrier.',
  'accueil.ajouterContact': 'Ajouter un contact',
  'accueil.nomCourtExemple': 'Nom court (ex. release)',
  'accueil.nomCourtAria': 'Nom court du contact',
  'accueil.quiDesigne': 'Qui désigne-t-il ? Un agent, ou plusieurs pour un groupe.',
  'accueil.notePlaceholder': 'Note (facultatif) : quand lui écrire',
  'accueil.noteAria': 'Note du contact',
  'accueil.ajouter': 'Ajouter',
  'accueil.ajouterNomme': ' « {propose} »',
  'accueil.annuler': 'Annuler',
} as const;
