import type { FR_ACCUEIL } from '../fr/accueil.ts';

type ClesAccueil = keyof typeof FR_ACCUEIL;
export const EN_ACCUEIL: Record<ClesAccueil, string> = {
  'accueil.copierInviteAgent': 'Copy the invite for the agent',
  'accueil.dansQuelProjet': 'Which project?',
  'accueil.projetExistant': 'Existing project',
  'accueil.nouveauProjetExemple': 'New project (e.g. talos)',
  'accueil.nouveauProjet': 'New project',
  'accueil.sansProjet': 'No project',
  // les espaces finales/initales comptent, comme en français
  'accueil.projetSeraAvant': 'The project will be called ',
  'accueil.projetSeraApres': ' (lowercase, no spaces).',
  'accueil.inviteCopiee': 'Invite copied',
  'accueil.copierInvite': 'Copy the invite',
  'accueil.inviteAideCopiee': 'Paste it into your agent\'s chat: it creates its account on its own, in this project.',
  'accueil.inviteAide': 'You get a text to paste into your agent\'s chat. It reads its project there and creates its account on its own.',
  'accueil.copieRefusee': 'Your browser refused the automatic copy: select this text and copy it.',
  'accueil.connecterProjet': 'Connect a project',
  'accueil.choisirDossierProjet': 'Choose the project folder…',
  'accueil.cheminLocalDepot': 'Local path of the repository',
  'accueil.nomProjetExemple': 'Project name (e.g. talos)',
  'accueil.nomProjet': 'Project name',
  'accueil.connecter': 'Connect',
  'accueil.connecterAide': 'Attaches a project folder to the mailbox and sets up this machine\'s AI tools. Next, you\'ll copy the invite to send to the project\'s agents.',
  'accueil.projetConnecteTitre': 'Project "{projet}" connected',
  'accueil.dossierConnecteTitre': 'Folder connected',
  'accueil.modaleInviteTitre': 'Last step: invite your agents.',
  'accueil.modaleInviteAvant': 'Copy the invite, then paste it into the chat of the agent — or of each agent — working on this project. Each one creates its account ',
  'accueil.modaleInviteDans': 'in',
  'accueil.modaleInviteApres': 'on its own, and appears here.',
  'accueil.inviteCopieeColler': 'Invite copied — paste it to your agent',
  'accueil.modaleInviteGroupe': 'You can paste it to several agents: the same invite works for everyone in the project.',
  'accueil.outilsPrets': 'AI tools ready on this machine: {hotes}.',
  'accueil.fermer': 'Close',
  'accueil.terminer': 'Done',
  'accueil.boiteRubrique': 'Mailbox',
  'accueil.creerBoite': 'Create the mailbox',
  'accueil.choisirDossierBoite': 'Choose the mailbox folder…',
  'accueil.dossierPartageBoite': 'Shared folder for the mailbox',
  'accueil.creerBoiteAide': 'Creates the mailbox in this folder and opens it. Choose a shared folder, visible from all your machines.',
  'accueil.fenetreOuverte': 'File chooser open…',
  'accueil.choisirDossierAide': 'Choose the folder in the window that just opened. If you can\'t see it, it\'s behind this page.',
  'accueil.collerChemin': '…or paste the path',
  'accueil.cePoste': 'This machine',
  'accueil.aucunOutil': 'No AI tool found on this machine (Claude Code, Codex, Kimi Code, Antigravity, Cursor).',
  'accueil.pretsTitle': 'These tools read and write the mailbox on their own',
  'accueil.prets': 'Ready: {noms}',
  'accueil.aPreparer': 'To set up: {noms}',
  'accueil.preparerPoste': 'Set up this machine',
  'accueil.preparerAide': 'Hooks the mailbox into these tools without erasing any of their settings. Takes effect the next time they open.',
  'accueil.eteindreBoite': 'Shut down the mailbox',
  'accueil.eteindreAide': 'Closes this window onto the mailbox. Your agents keep writing to each other.',
  'accueil.boiteDemo': 'Demo mailbox (no mailbox chosen yet)',
  'accueil.boiteChemin': 'Mailbox: {chemin}',
  'accueil.ouvrirMaBoite': 'Open my mailbox',
  'accueil.changerBoite': 'Switch mailbox',
  'accueil.ouvrirCetteBoite': 'Open this mailbox',
  'accueil.changerBoiteAide': 'Points this machine at the shared folder where the mailbox lives (on your NAS, for instance). Do the same on every machine, to the same folder: everyone then reads the same mail.',
  'accueil.agentAria': 'Agent {nom}',
  'accueil.adresseTitle': 'Its address in the mailbox',
  'accueil.fermerFiche': 'Close the card',
  'accueil.aucuneInfo': 'No information on this account.',
  'accueil.alerteReprise': 'This account was taken over from an old mailbox: its agent never took it back, so it doesn\'t check its mail. ',
  'accueil.alerteAttente__1': '{n} message is waiting for it {anciennete}. ',
  'accueil.alerteAttente__n': '{n} messages are waiting for it {anciennete}. ',
  'accueil.alerteInvite': 'If it doesn\'t reply, send it its invite: it will take its account back from its working folder.',
  'accueil.projetRubrique': 'Project',
  'accueil.carnet': 'Address book',
  'accueil.aucunContact': 'No contact. A contact gives a short name to an agent, or a group, it writes to often.',
  'accueil.retirerContactAria': 'Remove the contact {alias}',
  'accueil.retirerContactTitle': 'Remove this contact',
  'accueil.projetAdresseAvant': 'Its address already carries its project (',
  'accueil.projetAdresseApres': '): it can\'t be filed anywhere else.',
  'accueil.rangeDans': 'Filed under {projet}.',
  'accueil.sansProjetCompte': 'No project: account shared across all projects.',
  'accueil.projetAgentAria': 'Agent\'s project',
  'accueil.optionSansProjet': 'No project (shared account)',
  'accueil.nouveauProjetOption': 'New project…',
  'accueil.ranger': 'File',
  'accueil.adresseNeChangePas': 'Its address doesn\'t change: its mail and address book stay valid.',
  'accueil.deuxComptes': 'Two accounts, one agent?',
  'accueil.fusionnerDansAria': 'Merge this account into',
  'accueil.fusionnerDansOption': 'Merge this account into…',
  'accueil.fusionner': 'Merge',
  'accueil.fusionAvant': '"{nom}" will be closed: its pending mail moves to ',
  'accueil.fusionApres': ', and anything still written to its address ends up there. Messages already sent don\'t change.',
  'accueil.copierSonInvite': 'Copy its invite',
  'accueil.aCollerAide': 'To paste into this agent\'s chat: it takes this account back and checks its mail.',
  'accueil.ajouterContact': 'Add a contact',
  'accueil.nomCourtExemple': 'Short name (e.g. release)',
  'accueil.nomCourtAria': 'Contact\'s short name',
  'accueil.quiDesigne': 'Who does it stand for? One agent, or several for a group.',
  'accueil.notePlaceholder': 'Note (optional): when to write to it',
  'accueil.noteAria': 'Contact note',
  'accueil.ajouter': 'Add',
  'accueil.ajouterNomme': ' "{propose}"',
  'accueil.annuler': 'Cancel',
};
