import type { FR_COQUILLE } from '../fr/coquille.ts';

type ClesCoquille = keyof typeof FR_COQUILLE;
export const EN_COQUILLE: Record<ClesCoquille, string> = {
  'coquille.eteinteTitre': 'The mailbox is off',
  'coquille.eteinteTexteAvant': 'Your agents keep writing to each other: only this window has stopped. To reopen it, double-click the ',
  'coquille.eteinteTexteApres': ' icon. You can close this tab.',
  'coquille.obsoleteAvant': 'The running mailbox predates this page: close it and start it again (double-click the ',
  'coquille.obsoleteApres': ' icon) to restore all features.',
  'coquille.creationLectureSeule': 'Mailbox is read-only (legacy Markdown mailbox) — migrate it to JSON (messenger.py migrate) to create projects.',
  'coquille.creationIndisponible': 'Creation is unavailable for this mailbox.',
  'coquille.boiteDemonstration': 'Demo mailbox',
  'coquille.boitePartagee': 'Shared mailbox',
  'coquille.nouveaux__1': '{n} NEW',
  'coquille.nouveaux__n': '{n} NEW',
  'coquille.veilleActive': 'Watch active',
  'coquille.veilleSuspendue': 'Watch paused',
  'coquille.veilleSuspendre': 'Pause the automatic mail check',
  'coquille.veilleReprendre': 'Resume the automatic mail check',
  'coquille.notificationsIndisponibles': 'System notifications unavailable',
  'coquille.notificationsActives': 'System notifications on: every message that comes in is announced — click to turn off',
  'coquille.notificationsCoupees': 'System notifications off — click to turn them back on',
  'coquille.themeSombre': 'Switch to dark',
  'coquille.themeClair': 'Switch to light',
  'coquille.agirEnTant': 'You are acting as {compte}',
  'coquille.navBoites': 'Mailboxes',
  'coquille.tousMessages': 'All messages',
  'coquille.reponses': 'Threads',
  'coquille.avecPieceJointe': 'With attachment',
  'coquille.adressesA': 'Addressed to {compte}',
  'coquille.proprietaire': 'Owner',
  'coquille.projets': 'Projects',
  'coquille.tousProjets': 'All projects',
  'coquille.agents': 'Agents',
  'coquille.projetAgents__1': '{n} agent',
  'coquille.projetAgents__n': '{n} agents',
  'coquille.projetMessages__1': '{n} message',
  'coquille.projetMessages__n': '{n} messages',
  'coquille.projetEchanges': 'including exchanges with other projects',
  'coquille.projetNouveaux__1': '{n} new',
  'coquille.projetNouveaux__n': '{n} new',
  'coquille.voirTousProjets': 'Show all projects',
  'coquille.voirProjetSeul': 'Show only the {projet} project',
  'coquille.groupeVide': 'No agents yet — copy the invite and paste it to your agent.',
  'coquille.agentSilencieux': 'silent',
  'coquille.agentDernier': 'last {quand}',
  'coquille.agentEnvois__1': '{n} message sent',
  'coquille.agentEnvois__n': '{n} messages sent',
  'coquille.agentCarnet': 'address book: {carnet}',
  'coquille.agentEnAttente__1': '{n} waiting',
  'coquille.agentEnAttente__n': '{n} waiting',
  'coquille.agentAttenteDepuis': 'The oldest has been waiting {anciennete}',
  'coquille.releve': 'Mail check',
  'coquille.releveExplication': 'Any write to the mailbox wakes the agent in session; otherwise it checks mail at the next start.',
  'coquille.relevePremiere': 'First mail check…',
  'coquille.releveDerniere': 'Last mail check {heure} · {constat}',
  'coquille.messages': 'Messages',
  'coquille.listeVide': 'The mailbox is empty.',
  'coquille.listeAucun': 'No messages match.',
  'coquille.panneTitre': 'The mailbox could not be read',
  'coquille.panneIndique': 'Point the interface at the mailbox: ',
  'coquille.panneDans': ' in ',
  'coquille.panneOu': ', or ',
  'coquille.panneTerminal': 'The details are in the terminal running ',
};
