import type { FR_MESSAGE } from '../fr/message.ts';

type ClesMessage = keyof typeof FR_MESSAGE;
export const EN_MESSAGE: Record<ClesMessage, string> = {
  'message.statut.nouveau': 'new',
  'message.statut.lu': 'read',
  'message.statut.traite': 'done',
  'message.filtre.toutes': 'All',
  'message.filtre.recherche': 'Subject, id, attachment',
  'message.filtre.recherche-aria': 'Search the mailbox',
  'message.detail.aria': 'Message',
  'message.detail.aucun': 'Nothing to show.',
  'message.detail.de': 'From',
  'message.detail.a': 'To',
  'message.detail.statut': 'Status',
  'message.detail.corps': 'Body',
  'message.detail.pj': 'Attachment',
  'message.detail.fil': 'Thread',
  'message.detail.corps-vide': 'None — the subject says it all.',
  'message.detail.pj-vide': 'None — the body says it all.',
  'message.detail.pj-absente': 'missing',
  'message.detail.pj-absente-infobulle': 'This file is not in the mailbox folder.',
  'message.detail.fil-vide': 'No replies yet.',
  'message.detail.fuseau': 'Paris',
  'message.detail.pas-lu': 'has not read it yet',
  'message.detail.marque': 'marked it {statut}',
  'message.detail.envoye': 'sent by {par} on {date}',
  'message.detail.statut-par': '{statut} by {par} on {date}',
  'message.action.lecture-seule': 'Read-only',
  'message.action.lecture-seule-infobulle': 'Legacy Markdown mailbox: migrate it to JSON to act (messenger.py migrate).',
  'message.action.terminal': 'Final status',
  'message.action.reserve': 'Reserved for {destinataires}',
  'message.action.reserve-infobulle': 'Only a recipient can change the status.',
  'message.action.marquer-lu': 'Mark read',
  'message.action.marquer-traite': 'Mark done',
  'message.trafic.aria': 'Traffic for the day',
  'message.trafic.titre': 'Traffic on {jour}',
  'message.trafic.messages__1': '{n} message',
  'message.trafic.messages__n': '{n} messages',
  'message.trafic.agents__1': '{n} agent',
  'message.trafic.agents__n': '{n} agents',
  'message.trafic.fuseau-paris': 'Paris time',
  'message.trafic.fuseau-local': 'local time',
  'message.trafic.vide': 'No traffic that day.',
  'message.trafic.point': '{heure} · {de} → {destinataires} · {titre}',
  'message.pied.total__1': '{n} message',
  'message.pied.total__n': '{n} messages',
  'message.pied.nouveau__1': '{n} new',
  'message.pied.nouveau__n': '{n} new',
  'message.pied.pj__1': '{n} attachment',
  'message.pied.pj__n': '{n} attachments',
  'message.pied.demonstration': 'Demo — your mailbox: MESSENGER_BOX in ui/.env.local',
  'message.pied.source': 'Source: {nom}',
  'message.pied.markdown': ' · converted to JSON · read-only',
  'message.etiquette.commun': 'shared',
  'message.etiquette.commun-infobulle': 'Account shared by all projects',
  'message.etiquette.projet': 'Project {nom}',
};
