"""Human-readable mailbox view regenerated after every write: `boite.md`."""
from __future__ import annotations

import os

from ...domain import Boite, Message
from .fichiers import ecrire_atomique


class VueMarkdown:
    """Publish the mailbox as Markdown, newest first. This file is never read back."""

    def __init__(self, chemin: str, nom_boite: str, nom_manifeste: str) -> None:
        self._chemin = chemin
        self._nom_boite = nom_boite
        self._nom_manifeste = nom_manifeste

    def __call__(self, boite: Boite) -> None:
        ecrire_atomique(self._chemin, rendre(boite, self._nom_boite, self._nom_manifeste))

    @staticmethod
    def pour(chemin_boite: str) -> "VueMarkdown":
        racine = os.path.splitext(chemin_boite)[0]
        return VueMarkdown(racine + ".md", os.path.basename(chemin_boite),
                           os.path.basename(racine + ".manifest.json"))


def rendre(boite: Boite, nom_boite: str, nom_manifeste: str) -> str:
    lignes = [
        "# Agent Mailbox—generated view",
        "",
        f"> Human-readable view regenerated by `messenger.py` after every write. **Do not edit:** "
        f"the source is `{nom_boite}`. Accounts: `{nom_manifeste}`.",
        "",
        "## Messages",
        "",
    ]
    for m in boite.recents():
        lignes.extend(_bloc(m))
    return "\n".join(lignes)


def _statut(m: Message) -> str:
    """La vue d'ensemble, puis qui a avancé — un statut appartient à chaque destinataire."""
    avances = [f"{d} {s}" for d, s in m.statuts.items() if s != m.statut]
    return m.statut + (f" (including {', '.join(avances)})" if avances else "")


def _bloc(m: Message) -> list:
    pj = f"[{m.pj}]({m.pj})" if m.pj else "—"
    return [
        f"### {m.id} · {m.titre}",
        f"**From** {m.de} → **To** {', '.join(m.a)} · **Status** {_statut(m)} · **Attachment** {pj}",
        *m.corps,
        "",
    ]
